# Generated by Django 4.0.4 on 2022-04-29 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='fist_name',
            new_name='first_name',
        ),
    ]
