# Generated by Django 4.0.4 on 2022-04-29 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_fist_name_newuser_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='usertypes',
            field=models.CharField(choices=[('employer', 'EMPLOYER'), ('employee', 'EMPLOYEE')], default='employer', max_length=300),
        ),
    ]
