# Generated by Django 4.0.4 on 2022-05-02 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_newuser_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='usertypes',
        ),
    ]
