# Generated by Django 4.0.4 on 2022-05-02 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_newuser_usertypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='usertypes',
            field=models.CharField(choices=[('employer', 'EMPLOYER'), ('employee', 'EMPLOYEE')], default='employer', max_length=300),
        ),
    ]
