# Generated by Django 4.0.4 on 2022-05-02 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_newuser_usertypes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='usertypes',
        ),
    ]
