# Generated by Django 4.0.4 on 2022-05-02 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_remove_newuser_usertypes'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='usertypes',
            field=models.CharField(choices=[('employer', 'EMPLOYER'), ('employee', 'EMPLOYEE')], default='employer', max_length=300),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
