# Generated by Django 4.0.4 on 2022-05-20 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_newuser_first_name_alter_newuser_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='categoryy',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
