# Generated by Django 4.0.4 on 2022-05-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_alter_application_jobid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='jobid',
            field=models.CharField(default=1, max_length=250),
        ),
    ]
